name = "dubai-app-front"
compatibility_date = "2024-11-01"
pages_build_output_dir = ".open-next"
compatibility_flags = ["nodejs_compat"]

# KV namespace for message storage
[[kv_namespaces]]
binding = "WEBHOOK_KV"
id = "2d0ed139149e47e0a6fce80719d2d44f"

# Queue producer (for message ingestion)
[[queues.producers]]
binding = "MESSAGE_QUEUE"
queue = "dubai-app-queue"

# Durable Object binding (Pages must reference a Worker via script_name)
[[durable_objects.bindings]]
name = "SESSIONS"            # used in Pages Functions as env.SESSIONS
class_name = "SessionHub"    # DO class name defined in the Worker
script_name = "session-hub"  # EXACT Worker name that owns the DO