name = "dubai-app-front"
compatibility_date = "2024-11-01"
pages_build_output_dir = ".open-next"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "WEBHOOK_KV"
id = "2d0ed139149e47e0a6fce80719d2d44f"

[[kv_namespaces]]
binding = "CHART_KV"
id = "254eda49b33c49079029e5612dc45b94"

[[queues.producers]]
binding = "MESSAGE_QUEUE"
queue = "dubai-app-queue"

[[durable_objects.bindings]]
name = "SESSIONS"
class_name = "SessionHub"
script_name = "session-hub"   # ✅ matches the Worker you deployed

[[kv_namespaces]]
binding = "MANIFEST_KV"
id = "3bd9bcdc58f442068119d68264b14691"
