name = "dubai-dashboard-api"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[vars]
LEAGUE_JSON_URL = "https://example.com/league.json"
RENT_PPM2_JSON_URL = "https://example.com/rent_ppm2.json"
PTR_JSON_URL = "https://example.com/ptr.json"
